import type { LogLine } from "@/entities/log/types";
import { formatInstant } from "@/shared/lib/datetime";

/** Flat meta for AI Context MD — no Log domain model. */
export interface AiContextMeta {
  clusterId?: string;
  namespace?: string;
  pod?: string;
  container?: string;
  previous?: boolean;
  sinceSeconds?: number;
  tailLines?: number;
  /** Human source label fallback, e.g. ns/pod/container */
  sourceLabel?: string;
}

export interface BuildAiContextMdInput {
  meta: AiContextMeta;
  lines: LogLine[];
  /** Focus line (search hit or selection center). */
  focusLineNumber?: number;
  searchQuery?: string;
  /** Lines before/after focus when slicing. Default 50. */
  contextRadius?: number;
}

/**
 * Standard Markdown package for external AI Coder.
 * Lancer does not call models — only produces this text.
 */
export function buildAiContextMarkdown(input: BuildAiContextMdInput): string {
  const radius = input.contextRadius ?? 50;
  const focus =
    input.focusLineNumber ??
    input.lines[Math.floor(input.lines.length / 2)]?.lineNumber;

  const slice =
    focus === undefined
      ? input.lines
      : input.lines.filter(
          (l) => l.lineNumber >= focus - radius && l.lineNumber <= focus + radius,
        );

  const firstTs = slice[0]?.timestamp;
  const lastTs = slice[slice.length - 1]?.timestamp;
  const timeRange =
    firstTs && lastTs
      ? `${formatInstant(firstTs, "yyyy-MM-dd HH:mm:ss")} ~ ${formatInstant(lastTs, "yyyy-MM-dd HH:mm:ss")}`
      : "—";

  const m = input.meta;
  const source =
    m.sourceLabel ??
    ([m.namespace, m.pod, m.container].filter(Boolean).join("/") || "—");

  const linesOut = slice.map((l) => {
    const ts = l.timestamp
      ? formatInstant(l.timestamp, "yyyy-MM-dd HH:mm:ss")
      : "";
    const mark = focus !== undefined && l.lineNumber === focus ? " ◀" : "";
    return `${String(l.lineNumber).padStart(6, " ")}  ${ts}  [${l.level}]  ${l.message}${mark}`;
  });

  return [
    "# Lancer AI Context",
    "",
    "> Generated by Lancer for an external AI Coder. Lancer itself does not run a model.",
    "",
    "## Meta",
    "",
    `| Field | Value |`,
    `| --- | --- |`,
    `| cluster | ${m.clusterId ?? "—"} |`,
    `| source | ${source} |`,
    `| namespace | ${m.namespace ?? "—"} |`,
    `| pod | ${m.pod ?? "—"} |`,
    `| container | ${m.container ?? "—"} |`,
    `| previous | ${m.previous ? "yes" : "no"} |`,
    `| sinceSeconds | ${m.sinceSeconds && m.sinceSeconds > 0 ? m.sinceSeconds : "—"} |`,
    `| tailLines | ${m.tailLines !== undefined ? m.tailLines : "—"} |`,
    `| focusLine | ${focus ?? "—"} |`,
    `| searchQuery | ${input.searchQuery?.trim() ? input.searchQuery.trim() : "—"} |`,
    `| timeRange | ${timeRange} |`,
    `| lineCount | ${slice.length} |`,
    "",
    "## Logs",
    "",
    "```log",
    ...linesOut,
    "```",
    "",
    "## Ask (for AI Coder)",
    "",
    "Based on the log excerpt above:",
    "1. What is the most likely root cause?",
    "2. Which local source files should I inspect?",
    "3. What concrete code/config changes would fix it?",
    "",
  ].join("\n");
}
